name: LFS Migration
on:
  workflow_dispatch:
    inputs:
      LFS files:
        description: 'A comma seperated list of file extensions to convert to LFS (e.g. *.file1, *.file2)'     
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create local tracking branches
        run: | 
          for branch in $(git for-each-ref --shell --format="%(refname)" | sed "s@'@@g" | grep -v 'main\|HEAD'); do 
            shortref=$(echo "${branch}" | sed 's@refs/remotes/origin/@@g'); 
            git branch --track "${shortref}" "${branch}";
          done

      - name: LFS migration / import
        run: |
          time git lfs migrate import --everything --include="{{ }}"

      - name: expire reflog
        run: |
          time git reflog expire --expire=now --all
          
      - name: garbage collect / aggressive
        run: |
          time git gc --prune=now --aggressive
          
      - name: Push LFS files to origin
        run: |
          time git lfs push origin --all
      
      # in theory we could push --all however any issues that surface could be branch related 
      # and in my experience while it's a little quicker to try everything, any failure will 
      # result in signigant loss of time, also this allows us to push everything else if a single
      # issue is found.
      - name: Push everything in each branch
        run: | 
          for branch in $(git for-each-ref --shell --format="%(refname)" | sed "s@'@@g" | grep -v 'main\|HEAD'); do
              shortref=$(echo "${branch}" | sed 's@refs/remotes/origin/@@g');
              git checkout "${shortref}";
              git reset --hard;
              git clean -f -d;
              time git lfs push origin "${shortref}" --all;
              time git push;
          done
